backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
collections:
- name: "machine-learning"
  label: "Machine learning"
  folder: "content/machine-learning"
  create: true
